// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACTrIa3MlCROckndmYqd7ZgeFKwZRtwkw',
    appId: '1:1082872368147:web:2a996ff31b677ea55c03e6',
    messagingSenderId: '1082872368147',
    projectId: 'my-fcm-be0d7',
    authDomain: 'my-fcm-be0d7.firebaseapp.com',
    storageBucket: 'my-fcm-be0d7.firebasestorage.app',
    measurementId: 'G-EVHXYB6KVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALK1q3y6niU_iGk5y9xM2Gvhc74we95WA',
    appId: '1:1082872368147:android:fc4339a59a9691c45c03e6',
    messagingSenderId: '1082872368147',
    projectId: 'my-fcm-be0d7',
    storageBucket: 'my-fcm-be0d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX4i6ggUyty7UnmJTn-um3fK1uVdf40Tc',
    appId: '1:1082872368147:ios:c22630654ec29f2e5c03e6',
    messagingSenderId: '1082872368147',
    projectId: 'my-fcm-be0d7',
    storageBucket: 'my-fcm-be0d7.firebasestorage.app',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX4i6ggUyty7UnmJTn-um3fK1uVdf40Tc',
    appId: '1:1082872368147:ios:c22630654ec29f2e5c03e6',
    messagingSenderId: '1082872368147',
    projectId: 'my-fcm-be0d7',
    storageBucket: 'my-fcm-be0d7.firebasestorage.app',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACTrIa3MlCROckndmYqd7ZgeFKwZRtwkw',
    appId: '1:1082872368147:web:d6f8344ad2c7858e5c03e6',
    messagingSenderId: '1082872368147',
    projectId: 'my-fcm-be0d7',
    authDomain: 'my-fcm-be0d7.firebaseapp.com',
    storageBucket: 'my-fcm-be0d7.firebasestorage.app',
    measurementId: 'G-H8XQSNQ31R',
  );
}
